### ISSUE TITLE
crashes when framing osana

### ISSUE THREAD

**Issue by dgt8607** [ScottMichaud/YandereSimulatorLauncher2#11]
when i try to frame osana for murder and kill horada puresu the game crashes or freeses once the police arrive and match the blood to horada

**Comment by ScottMichaud** [comment]
Sorry for the inconvenience! This GitHub is about the launcher specifically.

Please report issues about the game, itself, directly to YandereDev at the following address:
https://yanderedev.wordpress.com/downloads/
