### ISSUE TITLE
Unable to launch the game

### ISSUE THREAD

**Issue by skybird23333** [ScottMichaud/YandereSimulatorLauncher2#15]
# Steps to reproduce
1. Download the latest version of the launcher from the Yandere Simulator website. (v2.8.0 as given in README)
2. Open the launcher.
3. Press install, and wait for it to download the game.

# Expected Behaviour
The game is able to launch as expected.

# Actual outcome
Returns the following error:
![image](https://user-images.githubusercontent.com/58811224/102999782-a7d91500-4564-11eb-9af1-0c34272eda05.png)

When attempting to play the game:
![image](https://user-images.githubusercontent.com/58811224/102999809-b45d6d80-4564-11eb-96b2-2f18651ece1e.png)

# Notes
- The "Cannot download game" error does not display when launcher is started from the .zip file.
- Releases downloaded directly from the Yandere Simulator website also appear to be broken and I am not able to extract the files from them.

**Comment by ScottMichaud** [comment]
Thanks for the report. Looks like YandereDev accidentally released a build (at least to Mega) that failed to package. I reported it to him.

**Comment by ScottMichaud** [comment]
Fixed by YandereDev.
