### ISSUE TITLE
Launcher lost game after PC reset

### ISSUE THREAD

**Issue by Termisher** [ScottMichaud/YandereSimulatorLauncher2#19]
my game disapeard.

**Comment by ScottMichaud** [comment]
So far every report of the game disappearing has been related to Issue #3.

Please ensure that you unzip YandereSimulatorLauncher2.exe from YandereSimLauncher.zip before running the application. The launcher works by unpacking the game into the launcher's folder (technically its working directory). The problem with running applications from within ZIP files is that Windows runs them with the Temporary Files Folder as their working directory.

This means that, if you run the launcher from within the zip, the game will be downloaded into the temporary files folder alongside the launcher.

This was intended as a feature -- it allows people to unpack the launcher onto a secondary hard drive or a USB drive, and it allows them to run the game without being an administrator. Unfortunately, Windows makes it very easy to accidentally install the game into the temporary files folder, which causes issues like this.

If you did extract YandereSimulatorLauncher2.exe into a folder that you have full read/write access over, then what do you see in the folder beside YandereSimulatorLauncher2.exe? Where is that folder located?

Thanks!

**Comment by ScottMichaud** [comment]
2.9.0 attempts to show a warning if you run from the temporary files folder.
