### ISSUE TITLE
Crashing screen issue with when before enter the school and it's slowing me down.

### ISSUE THREAD

**Issue by Marissapage18** [ScottMichaud/YandereSimulatorLauncher2#21]
I have a problem with loading screen it kept crashing screen. so I need your help please. and it bothers me.

**Comment by Marissapage18** [comment]
I just first download it and then when I first played it I just enter the school and is kept crashing loading screen.

**Comment by ScottMichaud** [comment]
This GitHub is for issues with the launcher, which is the window with the Install and Play buttons. Issues once the game has started is YandereDev's domain, although I might be able to help with this one.

Please send an email to scott@loosescrew.ca describing the bug.

If possible, please attach Player.log and Player-prev.log from the following folder:
%userprofile%\appdata\LocalLow\YandereDev\YandereSimulator

If you don't know how to acquire that, then I will give you better instructions in the email.

**Comment by Marissapage18** [comment]
https://static.wikia.nocookie.net/yandere-simulator/images/c/c6/Keyboard_controls.png/revision/latest?cb=20200201211803 this problem I have a problem with it.
