### ISSUE TITLE
Slow Download Speeds

### ISSUE THREAD

**Issue by MrJJSpazz** [ScottMichaud/YandereSimulatorLauncher2#9]
The launcher downloads the game at 10-50kbps while my speed test says 200mbps

**Comment by ScottMichaud** [comment]
It varies based on when you download. Sometimes I'm in the kilobytes per second. Sometimes I'm in the ~10s of megabytes per second. We use a free service, Mega.nz, and log you in anonymously. They throttle (and sometimes completely cut off) free users during overloaded times.

Ideally we'd run the service ourselves, but typical cloud hosting fees would be ~$10,000 (Backblaze) to $40,000 (AWS) per million downloads... so we make due with free services.

I'd like to add MediaFire as an optional back-end to the launcher, especially for the people who straight-up cannot access Mega, but I don't have a timeline for that yet. Too busy with other things. It's being tracked as #1 though.
